name: Nightly Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Update nightly tag
        uses: EndBug/latest-tag@latest
        if: github.ref == 'refs/heads/main'
        with:
          ref: nightly
      
      - name: Collect all files
        run: |
          mkdir ./RaidTablesViewer
          mkdir -p ./RaidTablesViewer/libs/LibDeflate
          mkdir -p ./RaidTablesViewer/libs/LibSerialize
          mkdir -p ./RaidTablesViewer/libs/LibStub
          mkdir -p ./RaidTablesViewer/img
          cp -r ./RaidTablesViewer.lua ./RaidTablesViewer.toc ./embeds.xml ./LICENSE ./README.md ./RaidTablesViewer
          cp -r ./img/RaidTables.png ./RaidTablesViewer/img/
          cp -r ./libs/LibDeflate/LibDeflate.lua ./libs/LibDeflate/LICENSE.txt ./RaidTablesViewer/libs/LibDeflate/
          cp -r ./libs/LibSerialize/LibSerialize.lua ./libs/LibSerialize/LICENSE ./RaidTablesViewer/libs/LibSerialize/
          cp -r ./libs/LibStub/LibStub.lua ./RaidTablesViewer/libs/LibStub/
          zip -r RaidTablesViewer-Nightly.zip ./RaidTablesViewer
          tar -czvf RaidTablesViewer-Nightly.tar.gz ./RaidTablesViewer
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          name: Nightly
          tag_name: nightly
          files: |
            RaidTablesViewer-Nightly.zip
            RaidTablesViewer-Nightly.tar.gz
