name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Collect all files
        run: |
          mkdir ./RaidTablesViewer
          cp -r ./RaidTablesViewer.lua ./RaidTablesViewer.toc ./embeds.xml ./LICENSE ./README.md ./RaidTablesViewer
          mkdir -p ./RaidTablesViewer/libs/LibDeflate
          cp -r ./libs/LibDeflate/LibDeflate.lua ./libs/LibDeflate/LICENSE.txt ./RaidTablesViewer/libs/LibDeflate/
          mkdir -p ./RaidTablesViewer/libs/LibSerialize
          cp -r ./libs/LibSerialize/LibSerialize.lua ./libs/LibSerialize/LICENSE ./RaidTablesViewer/libs/LibSerialize/
          mkdir -p ./RaidTablesViewer/libs/LibStub
          cp -r ./libs/LibStub/LibStub.lua ./RaidTablesViewer/libs/LibStub/
          mkdir -p ./RaidTablesViewer/img
          cp -r ./img/RaidTablesViewer.png ./RaidTablesViewer/img/
          mkdir -p ./RaidTablesViewer/fonts/UnicodeFont
          cp -r ./fonts/UnicodeFont/LICENSE.txt ./fonts/UnicodeFont/WarSansTT-Bliz-500.ttf ./RaidTablesViewer/fonts/UnicodeFont
          zip -r RaidTablesViewer-${{ github.ref_name }}.zip ./RaidTablesViewer
          tar -czvf RaidTablesViewer-${{ github.ref_name }}.tar.gz ./RaidTablesViewer
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          replacesArtifacts: true
          omitDraftDuringUpdate: true
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            RaidTablesViewer-${{ github.ref_name }}.zip
            RaidTablesViewer-${{ github.ref_name }}.tar.gz
